name: Alpha self-hosted Build

on:
  workflow_dispatch:
    inputs:
      runs_on:
        type: choice
        description: "Select runs-on"
        required: true
        default: "ARM64"
        options:
          - "ARM64"
          - "x64"
      target:
        type: choice
        description: "Select tartget"
        required: true
        default: "aarch64-apple-darwin"
        options:
          - "aarch64-apple-darwin"
          - "x86_64-apple-darwin"
  push:
    branches: [main]
    tags-ignore: [updater, alpha]
permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  alpha:
    runs-on: [self-hosted, "${{ inputs.runs_on }}"]
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: ${{ inputs.target}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.77.0

      - name: Add Rust Target
        run: rustup target add ${{ inputs.target}}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm check ${{ inputs.target}}

      - name: Download and install Apple intermediate certificates
        run: |
          curl -O https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer
          sudo security add-trusted-cert -d -r trustRoot -k ${HOME}/Library/Keychains/login.keychain-db DeveloperIDG2CA.cer

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          #加入以下内容为提交app到apple认证，当前会报错，已发邮件与apple沟通
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          #APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          #APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: alpha
          releaseName: "Clash Verge Rev Alpha"
          releaseBody: "More new features are now supported."
          releaseDraft: false
          prerelease: true
          tauriScript: pnpm
          args: --target ${{ inputs.target}}
